# starship - https://starship.rs/config/
command_timeout = 5000

format = """
[╭─](bold blue)$all$docker_context
[╰─](bold blue)$character"""

[docker_context]
disabled = false
symbol = "🐋 "
style = "bold blue"
only_with_files = true

[nodejs]
symbol = " "
format = "via [$symbol$version](bold green) "

[rust]
symbol = " "
format = "via [$symbol$version](bold red) "

[python]
symbol = " "
format = "via [$symbol$version](bold yellow) "

[git_branch]
symbol = " "
format = "on [$symbol$branch](bold purple) "

[git_status]
disabled = true

[package]
symbol = "📦 "
format = "via [$symbol$version](bold blue) "

[shell]
disabled = false
format = "$indicator"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
